endpoint: https://prometheus.prd.ee01.prd.azr.astra.netapp.io/api/v1/query
queries:
  - name: TotalActiveAccount
    query: |
      count(max by (account_id,account_name) (max_over_time(astra_nautilus_app_v6{state=~"protected|partial|atRisk|none|clone"}[1d])) > 0)
  - name: TotalPremiumAccount
    query: |
      count(count by (account_name) (count_over_time(astra_billing_account_total_minutes{terms="paid"}[1h])))
  - name: AccountDetailRegisteredUser
    query: |
      sort_desc(sum by (accountID,accountName,accountCreationTime,accountCompanyName) (max_over_time(user_total{job="identity", measurement="registered"}[1h])))
  - name: AccountDetailActivatedUser
    query: |
      sort_desc(sum by (accountID, accountName,accountCreationTime,accountCompanyName) (max_over_time(user_total{job="identity", measurement="activated"}[1h])))
  - name: AccountDetailBillingMinutes
    query: |
      sort_desc(sum by (accountID, accountName,accountCreationTime,accountCompanyName) (max_over_time(user_total{job="identity", measurement="activated"}[1h])))
  - name: TotalPaidMinutes
    query: |
      sum by (terms) (max_over_time(astra_billing_account_total_minutes{terms="paid"}[1h]))
  - name: TotalActivatedUsers
    query: |
      sum (max_over_time(user_total{measurement="activated",service="identity"}[1h]))
  - name: TotalApplications
    query: |
      sort_desc(sum(max by (account_id, account_name, state)(astra_nautilus_app_v6{state=~"protected|partial|atRisk|none"})))
  - name: FullyProtectedApplications
    query: |
      sort_desc(sum(max by (account_id, account_name)(astra_nautilus_app_v6{state="protected"})))
  - name: PartiallyProtectedApplications
    query: |
      sort_desc(sum(max by (account_id, account_name)(astra_nautilus_app_v6{state="partial"})))
  - name: NotProtectedApplications
    query: |
      sort_desc(sum(max by (account_id, account_name)(astra_nautilus_app_v6{state="none"})))
  - name: ClonedApplications
    query: |
      sort_desc(sum(max by (account_id, account_name)(astra_nautilus_app_v6{state="clone"})))
  - name: AtRiskApplications
    query: |
      sort_desc(sum(max by (account_id, account_name)(astra_nautilus_app_v6{state="atRisk"})))
  - name: TotalBackups
    query: |
      sort_desc(sum (max by (account_id,account_name) (max_over_time(astra_nautilus_backup_v6{}[1h]))))
  - name: TotalSnapshots
    query: |
      sort_desc(sum(max by (account_id,account_name,healthy) (max_over_time(astra_nautilus_snapshot_v6{}[1h]))))
  - name: TotalApplicationByAccount
    query: |
      sort_desc(sum by (account_id, account_name)(max by (account_id, account_name, state)(astra_nautilus_app_v6{state=~"protected|partial|atRisk|none"})))
  - name: TotalProtectedApplicationByAccount
    query: |
      sort_desc(sum by (account_id, account_name)(max by (account_id, account_name, state)(astra_nautilus_app_v6{state=~"protected"})))
  - name: TotalPartialProtectedApplicationByAccount
    query: |
      sort_desc(sum by (account_id, account_name)(max by (account_id, account_name, state)(astra_nautilus_app_v6{state=~"partial"})))
  - name: TotalAtRiskApplicationByAccount
    query: |
      sort_desc(sum by (account_id, account_name)(max by (account_id, account_name, state)(astra_nautilus_app_v6{state=~"atRisk"})))
  - name: TotalNotProtectedApplicationByAccount
    query: |
      sort_desc(sum by (account_id, account_name)(max by (account_id, account_name, state)(astra_nautilus_app_v6{state=~"none"})))
  - name: TotalClonedApplicationByAccount
    query: |
      sort_desc(sum by (account_id, account_name)(max by (account_id, account_name, state)(astra_nautilus_app_v6{state=~"clone"})))
  - name: TotalBackupsByAccount
    query: |
      sort_desc(sum by (account_id, account_name) (max by(account_id, account_name) (max_over_time(astra_nautilus_backup_v6{healthy=""}[1h]))))
  - name: TotalBackupPVCStorageUsedByAccount
    query: |
      sort_desc(sum by (account_id) (max by (account_id, backup_id) (max_over_time(astra_nautilus_backup_v6_total_bytes{}[1h]))))
  - name: TotalSnapshotByAccount
    query: |
      sort_desc(sum by (account_id) (max by (account_id, account_name) (max_over_time(astra_nautilus_snapshot_v6{healthy=""}[1h]))))
  - name: TotalNamespaceAvailable
    query: |
      sum(max by (account_id, account_name, state)(astra_nautilus_app_v6{state="namespace_available"}))
  - name: TotalNamespaceAvailableByAccount
    query: |
      sort_desc(sum by (account_name) (max by (account_id, account_name)(astra_nautilus_app_v6{state="namespace_available"})))
  - name: TotalNamespaceAssociated
    query: |
      sum(max by (account_id, account_name, state)(astra_nautilus_app_v6{state="namespace_associated"}))
  - name: TotalNamespaceAssociatedByAccount
    query: |
      sort_desc(sum by (account_name) (max by (account_id, account_name)(astra_nautilus_app_v6{state="namespace_associated"})))


