---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jsondata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: apachedrill
    app: apachedrill
    release: master-openjdk-17
  name: apachedrill
spec:
  ports:
    - name: http
      port: 8047
      protocol: TCP
      targetPort: 8047
    - name: jdbc
      port: 31010
      protocol: TCP
      targetPort: 31010
  selector:
    component: apachedrill
    app: apachedrill
  sessionAffinity: None
  type: "ClusterIP"
---
# Source: prometheus/templates/deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: apachedrill
    app: apachedrill
    release: master-openjdk-17
  name: apachedrill
spec:
  selector:
    matchLabels:
      component: apachedrill
      app: apachedrill
      release: master-openjdk-17
  replicas: 1
  strategy:
    type: Recreate
    rollingUpdate: null
  template:
    metadata:
      labels:
        component: apachedrill
        app: apachedrill
        release: master-openjdk-17
    spec:
      containers:
      - name: apachedrill
        image: apache/drill:master-openjdk-17
        imagePullPolicy: "IfNotPresent"
        resources:
          requests:
            memory: "1024Mi"
            cpu: "250m"
          limits:
            memory: "4096Mi"
            cpu: "1500m"
        ports:
        - containerPort: 8047
        - containerPort: 31010
        volumeMounts:
        - name: jsondata
          mountPath: /tmp/data
      - name: requester
        image: tli551/requester:latest
        imagePullPolicy: "IfNotPresent"
        resources:
          requests:
            memory: "1024Mi"
            cpu: "250m"
          limits:
            memory: "4096Mi"
            cpu: "1500m"
        volumeMounts:
        - name: jsondata
          mountPath: /tmp/data
      volumes:
      - name: jsondata
        persistentVolumeClaim:
          claimName: jsondata